// Generated by gencpp from file mode_msgs/ModeRequest.msg
// DO NOT EDIT!


#ifndef MODE_MSGS_MESSAGE_MODEREQUEST_H
#define MODE_MSGS_MESSAGE_MODEREQUEST_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace mode_msgs
{
template <class ContainerAllocator>
struct ModeRequest_
{
  typedef ModeRequest_<ContainerAllocator> Type;

  ModeRequest_()
    : mode()
    , input2(0)  {
    }
  ModeRequest_(const ContainerAllocator& _alloc)
    : mode(_alloc)
    , input2(0)  {
  (void)_alloc;
    }



   typedef std::basic_string<char, std::char_traits<char>, typename ContainerAllocator::template rebind<char>::other >  _mode_type;
  _mode_type mode;

   typedef int32_t _input2_type;
  _input2_type input2;





  typedef boost::shared_ptr< ::mode_msgs::ModeRequest_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::mode_msgs::ModeRequest_<ContainerAllocator> const> ConstPtr;

}; // struct ModeRequest_

typedef ::mode_msgs::ModeRequest_<std::allocator<void> > ModeRequest;

typedef boost::shared_ptr< ::mode_msgs::ModeRequest > ModeRequestPtr;
typedef boost::shared_ptr< ::mode_msgs::ModeRequest const> ModeRequestConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::mode_msgs::ModeRequest_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::mode_msgs::ModeRequest_<ContainerAllocator> >::stream(s, "", v);
return s;
}

} // namespace mode_msgs

namespace ros
{
namespace message_traits
{



// BOOLTRAITS {'IsFixedSize': False, 'IsMessage': True, 'HasHeader': False}
// {'std_msgs': ['/opt/ros/kinetic/share/std_msgs/cmake/../msg']}

// !!!!!!!!!!! ['__class__', '__delattr__', '__dict__', '__doc__', '__eq__', '__format__', '__getattribute__', '__hash__', '__init__', '__module__', '__ne__', '__new__', '__reduce__', '__reduce_ex__', '__repr__', '__setattr__', '__sizeof__', '__str__', '__subclasshook__', '__weakref__', '_parsed_fields', 'constants', 'fields', 'full_name', 'has_header', 'header_present', 'names', 'package', 'parsed_fields', 'short_name', 'text', 'types']




template <class ContainerAllocator>
struct IsFixedSize< ::mode_msgs::ModeRequest_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::mode_msgs::ModeRequest_<ContainerAllocator> const>
  : FalseType
  { };

template <class ContainerAllocator>
struct IsMessage< ::mode_msgs::ModeRequest_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::mode_msgs::ModeRequest_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::mode_msgs::ModeRequest_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::mode_msgs::ModeRequest_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::mode_msgs::ModeRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "c5de17c18096cd1c9d8e94b83a3ed370";
  }

  static const char* value(const ::mode_msgs::ModeRequest_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0xc5de17c18096cd1cULL;
  static const uint64_t static_value2 = 0x9d8e94b83a3ed370ULL;
};

template<class ContainerAllocator>
struct DataType< ::mode_msgs::ModeRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "mode_msgs/ModeRequest";
  }

  static const char* value(const ::mode_msgs::ModeRequest_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::mode_msgs::ModeRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "string mode\n\
int32 input2\n\
";
  }

  static const char* value(const ::mode_msgs::ModeRequest_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::mode_msgs::ModeRequest_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.mode);
      stream.next(m.input2);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct ModeRequest_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::mode_msgs::ModeRequest_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::mode_msgs::ModeRequest_<ContainerAllocator>& v)
  {
    s << indent << "mode: ";
    Printer<std::basic_string<char, std::char_traits<char>, typename ContainerAllocator::template rebind<char>::other > >::stream(s, indent + "  ", v.mode);
    s << indent << "input2: ";
    Printer<int32_t>::stream(s, indent + "  ", v.input2);
  }
};

} // namespace message_operations
} // namespace ros

#endif // MODE_MSGS_MESSAGE_MODEREQUEST_H
