// Generated by gencpp from file mode_msgs/Mode.msg
// DO NOT EDIT!


#ifndef MODE_MSGS_MESSAGE_MODE_H
#define MODE_MSGS_MESSAGE_MODE_H

#include <ros/service_traits.h>


#include <mode_msgs/ModeRequest.h>
#include <mode_msgs/ModeResponse.h>


namespace mode_msgs
{

struct Mode
{

typedef ModeRequest Request;
typedef ModeResponse Response;
Request request;
Response response;

typedef Request RequestType;
typedef Response ResponseType;

}; // struct Mode
} // namespace mode_msgs


namespace ros
{
namespace service_traits
{


template<>
struct MD5Sum< ::mode_msgs::Mode > {
  static const char* value()
  {
    return "54307bda67f170e4b3f87373deb748d3";
  }

  static const char* value(const ::mode_msgs::Mode&) { return value(); }
};

template<>
struct DataType< ::mode_msgs::Mode > {
  static const char* value()
  {
    return "mode_msgs/Mode";
  }

  static const char* value(const ::mode_msgs::Mode&) { return value(); }
};


// service_traits::MD5Sum< ::mode_msgs::ModeRequest> should match 
// service_traits::MD5Sum< ::mode_msgs::Mode > 
template<>
struct MD5Sum< ::mode_msgs::ModeRequest>
{
  static const char* value()
  {
    return MD5Sum< ::mode_msgs::Mode >::value();
  }
  static const char* value(const ::mode_msgs::ModeRequest&)
  {
    return value();
  }
};

// service_traits::DataType< ::mode_msgs::ModeRequest> should match 
// service_traits::DataType< ::mode_msgs::Mode > 
template<>
struct DataType< ::mode_msgs::ModeRequest>
{
  static const char* value()
  {
    return DataType< ::mode_msgs::Mode >::value();
  }
  static const char* value(const ::mode_msgs::ModeRequest&)
  {
    return value();
  }
};

// service_traits::MD5Sum< ::mode_msgs::ModeResponse> should match 
// service_traits::MD5Sum< ::mode_msgs::Mode > 
template<>
struct MD5Sum< ::mode_msgs::ModeResponse>
{
  static const char* value()
  {
    return MD5Sum< ::mode_msgs::Mode >::value();
  }
  static const char* value(const ::mode_msgs::ModeResponse&)
  {
    return value();
  }
};

// service_traits::DataType< ::mode_msgs::ModeResponse> should match 
// service_traits::DataType< ::mode_msgs::Mode > 
template<>
struct DataType< ::mode_msgs::ModeResponse>
{
  static const char* value()
  {
    return DataType< ::mode_msgs::Mode >::value();
  }
  static const char* value(const ::mode_msgs::ModeResponse&)
  {
    return value();
  }
};

} // namespace service_traits
} // namespace ros

#endif // MODE_MSGS_MESSAGE_MODE_H
