// Generated by gencpp from file mode_msgs/ModeResponse.msg
// DO NOT EDIT!


#ifndef MODE_MSGS_MESSAGE_MODERESPONSE_H
#define MODE_MSGS_MESSAGE_MODERESPONSE_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace mode_msgs
{
template <class ContainerAllocator>
struct ModeResponse_
{
  typedef ModeResponse_<ContainerAllocator> Type;

  ModeResponse_()
    : output()
    , done(false)  {
    }
  ModeResponse_(const ContainerAllocator& _alloc)
    : output(_alloc)
    , done(false)  {
  (void)_alloc;
    }



   typedef std::basic_string<char, std::char_traits<char>, typename ContainerAllocator::template rebind<char>::other >  _output_type;
  _output_type output;

   typedef uint8_t _done_type;
  _done_type done;





  typedef boost::shared_ptr< ::mode_msgs::ModeResponse_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::mode_msgs::ModeResponse_<ContainerAllocator> const> ConstPtr;

}; // struct ModeResponse_

typedef ::mode_msgs::ModeResponse_<std::allocator<void> > ModeResponse;

typedef boost::shared_ptr< ::mode_msgs::ModeResponse > ModeResponsePtr;
typedef boost::shared_ptr< ::mode_msgs::ModeResponse const> ModeResponseConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::mode_msgs::ModeResponse_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::mode_msgs::ModeResponse_<ContainerAllocator> >::stream(s, "", v);
return s;
}

} // namespace mode_msgs

namespace ros
{
namespace message_traits
{



// BOOLTRAITS {'IsFixedSize': False, 'IsMessage': True, 'HasHeader': False}
// {'std_msgs': ['/opt/ros/kinetic/share/std_msgs/cmake/../msg']}

// !!!!!!!!!!! ['__class__', '__delattr__', '__dict__', '__doc__', '__eq__', '__format__', '__getattribute__', '__hash__', '__init__', '__module__', '__ne__', '__new__', '__reduce__', '__reduce_ex__', '__repr__', '__setattr__', '__sizeof__', '__str__', '__subclasshook__', '__weakref__', '_parsed_fields', 'constants', 'fields', 'full_name', 'has_header', 'header_present', 'names', 'package', 'parsed_fields', 'short_name', 'text', 'types']




template <class ContainerAllocator>
struct IsFixedSize< ::mode_msgs::ModeResponse_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::mode_msgs::ModeResponse_<ContainerAllocator> const>
  : FalseType
  { };

template <class ContainerAllocator>
struct IsMessage< ::mode_msgs::ModeResponse_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::mode_msgs::ModeResponse_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::mode_msgs::ModeResponse_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::mode_msgs::ModeResponse_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::mode_msgs::ModeResponse_<ContainerAllocator> >
{
  static const char* value()
  {
    return "13e336c7fb519e62ebdfdf364f5b1eba";
  }

  static const char* value(const ::mode_msgs::ModeResponse_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x13e336c7fb519e62ULL;
  static const uint64_t static_value2 = 0xebdfdf364f5b1ebaULL;
};

template<class ContainerAllocator>
struct DataType< ::mode_msgs::ModeResponse_<ContainerAllocator> >
{
  static const char* value()
  {
    return "mode_msgs/ModeResponse";
  }

  static const char* value(const ::mode_msgs::ModeResponse_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::mode_msgs::ModeResponse_<ContainerAllocator> >
{
  static const char* value()
  {
    return "string output\n\
bool done\n\
\n\
\n\
";
  }

  static const char* value(const ::mode_msgs::ModeResponse_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::mode_msgs::ModeResponse_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.output);
      stream.next(m.done);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct ModeResponse_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::mode_msgs::ModeResponse_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::mode_msgs::ModeResponse_<ContainerAllocator>& v)
  {
    s << indent << "output: ";
    Printer<std::basic_string<char, std::char_traits<char>, typename ContainerAllocator::template rebind<char>::other > >::stream(s, indent + "  ", v.output);
    s << indent << "done: ";
    Printer<uint8_t>::stream(s, indent + "  ", v.done);
  }
};

} // namespace message_operations
} // namespace ros

#endif // MODE_MSGS_MESSAGE_MODERESPONSE_H
