# This Python file uses the following encoding: utf-8
"""autogenerated by genpy from coms_msgs/Station.msg. Do not edit."""
import sys
python3 = True if sys.hexversion > 0x03000000 else False
import genpy
import struct

import genpy
import std_msgs.msg

class Station(genpy.Message):
  _md5sum = "c279ad04cbc81207a5714883b84da036"
  _type = "coms_msgs/Station"
  _has_header = True #flag to mark the presence of a Header object
  _full_text = """Header header
time headerstamp
float32 xMax
float32 xMin
float32 yMax
float32 yMin
float32 zMax
float32 zMin
bool flap_not_open_error

================================================================================
MSG: std_msgs/Header
# Standard metadata for higher-level stamped data types.
# This is generally used to communicate timestamped data 
# in a particular coordinate frame.
# 
# sequence ID: consecutively increasing ID 
uint32 seq
#Two-integer timestamp that is expressed as:
# * stamp.sec: seconds (stamp_secs) since epoch (in Python the variable is called 'secs')
# * stamp.nsec: nanoseconds since stamp_secs (in Python the variable is called 'nsecs')
# time-handling sugar is provided by the client library
time stamp
#Frame this data is associated with
# 0: no frame
# 1: global frame
string frame_id
"""
  __slots__ = ['header','headerstamp','xMax','xMin','yMax','yMin','zMax','zMin','flap_not_open_error']
  _slot_types = ['std_msgs/Header','time','float32','float32','float32','float32','float32','float32','bool']

  def __init__(self, *args, **kwds):
    """
    Constructor. Any message fields that are implicitly/explicitly
    set to None will be assigned a default value. The recommend
    use is keyword arguments as this is more robust to future message
    changes.  You cannot mix in-order arguments and keyword arguments.

    The available fields are:
       header,headerstamp,xMax,xMin,yMax,yMin,zMax,zMin,flap_not_open_error

    :param args: complete set of field values, in .msg order
    :param kwds: use keyword arguments corresponding to message field names
    to set specific fields.
    """
    if args or kwds:
      super(Station, self).__init__(*args, **kwds)
      #message fields cannot be None, assign default values for those that are
      if self.header is None:
        self.header = std_msgs.msg.Header()
      if self.headerstamp is None:
        self.headerstamp = genpy.Time()
      if self.xMax is None:
        self.xMax = 0.
      if self.xMin is None:
        self.xMin = 0.
      if self.yMax is None:
        self.yMax = 0.
      if self.yMin is None:
        self.yMin = 0.
      if self.zMax is None:
        self.zMax = 0.
      if self.zMin is None:
        self.zMin = 0.
      if self.flap_not_open_error is None:
        self.flap_not_open_error = False
    else:
      self.header = std_msgs.msg.Header()
      self.headerstamp = genpy.Time()
      self.xMax = 0.
      self.xMin = 0.
      self.yMax = 0.
      self.yMin = 0.
      self.zMax = 0.
      self.zMin = 0.
      self.flap_not_open_error = False

  def _get_types(self):
    """
    internal API method
    """
    return self._slot_types

  def serialize(self, buff):
    """
    serialize message into buffer
    :param buff: buffer, ``StringIO``
    """
    try:
      _x = self
      buff.write(_get_struct_3I().pack(_x.header.seq, _x.header.stamp.secs, _x.header.stamp.nsecs))
      _x = self.header.frame_id
      length = len(_x)
      if python3 or type(_x) == unicode:
        _x = _x.encode('utf-8')
        length = len(_x)
      buff.write(struct.pack('<I%ss'%length, length, _x))
      _x = self
      buff.write(_get_struct_2I6fB().pack(_x.headerstamp.secs, _x.headerstamp.nsecs, _x.xMax, _x.xMin, _x.yMax, _x.yMin, _x.zMax, _x.zMin, _x.flap_not_open_error))
    except struct.error as se: self._check_types(struct.error("%s: '%s' when writing '%s'" % (type(se), str(se), str(locals().get('_x', self)))))
    except TypeError as te: self._check_types(ValueError("%s: '%s' when writing '%s'" % (type(te), str(te), str(locals().get('_x', self)))))

  def deserialize(self, str):
    """
    unpack serialized message in str into this message instance
    :param str: byte array of serialized message, ``str``
    """
    try:
      if self.header is None:
        self.header = std_msgs.msg.Header()
      if self.headerstamp is None:
        self.headerstamp = genpy.Time()
      end = 0
      _x = self
      start = end
      end += 12
      (_x.header.seq, _x.header.stamp.secs, _x.header.stamp.nsecs,) = _get_struct_3I().unpack(str[start:end])
      start = end
      end += 4
      (length,) = _struct_I.unpack(str[start:end])
      start = end
      end += length
      if python3:
        self.header.frame_id = str[start:end].decode('utf-8')
      else:
        self.header.frame_id = str[start:end]
      _x = self
      start = end
      end += 33
      (_x.headerstamp.secs, _x.headerstamp.nsecs, _x.xMax, _x.xMin, _x.yMax, _x.yMin, _x.zMax, _x.zMin, _x.flap_not_open_error,) = _get_struct_2I6fB().unpack(str[start:end])
      self.flap_not_open_error = bool(self.flap_not_open_error)
      self.headerstamp.canon()
      return self
    except struct.error as e:
      raise genpy.DeserializationError(e) #most likely buffer underfill


  def serialize_numpy(self, buff, numpy):
    """
    serialize message with numpy array types into buffer
    :param buff: buffer, ``StringIO``
    :param numpy: numpy python module
    """
    try:
      _x = self
      buff.write(_get_struct_3I().pack(_x.header.seq, _x.header.stamp.secs, _x.header.stamp.nsecs))
      _x = self.header.frame_id
      length = len(_x)
      if python3 or type(_x) == unicode:
        _x = _x.encode('utf-8')
        length = len(_x)
      buff.write(struct.pack('<I%ss'%length, length, _x))
      _x = self
      buff.write(_get_struct_2I6fB().pack(_x.headerstamp.secs, _x.headerstamp.nsecs, _x.xMax, _x.xMin, _x.yMax, _x.yMin, _x.zMax, _x.zMin, _x.flap_not_open_error))
    except struct.error as se: self._check_types(struct.error("%s: '%s' when writing '%s'" % (type(se), str(se), str(locals().get('_x', self)))))
    except TypeError as te: self._check_types(ValueError("%s: '%s' when writing '%s'" % (type(te), str(te), str(locals().get('_x', self)))))

  def deserialize_numpy(self, str, numpy):
    """
    unpack serialized message in str into this message instance using numpy for array types
    :param str: byte array of serialized message, ``str``
    :param numpy: numpy python module
    """
    try:
      if self.header is None:
        self.header = std_msgs.msg.Header()
      if self.headerstamp is None:
        self.headerstamp = genpy.Time()
      end = 0
      _x = self
      start = end
      end += 12
      (_x.header.seq, _x.header.stamp.secs, _x.header.stamp.nsecs,) = _get_struct_3I().unpack(str[start:end])
      start = end
      end += 4
      (length,) = _struct_I.unpack(str[start:end])
      start = end
      end += length
      if python3:
        self.header.frame_id = str[start:end].decode('utf-8')
      else:
        self.header.frame_id = str[start:end]
      _x = self
      start = end
      end += 33
      (_x.headerstamp.secs, _x.headerstamp.nsecs, _x.xMax, _x.xMin, _x.yMax, _x.yMin, _x.zMax, _x.zMin, _x.flap_not_open_error,) = _get_struct_2I6fB().unpack(str[start:end])
      self.flap_not_open_error = bool(self.flap_not_open_error)
      self.headerstamp.canon()
      return self
    except struct.error as e:
      raise genpy.DeserializationError(e) #most likely buffer underfill

_struct_I = genpy.struct_I
def _get_struct_I():
    global _struct_I
    return _struct_I
_struct_3I = None
def _get_struct_3I():
    global _struct_3I
    if _struct_3I is None:
        _struct_3I = struct.Struct("<3I")
    return _struct_3I
_struct_2I6fB = None
def _get_struct_2I6fB():
    global _struct_2I6fB
    if _struct_2I6fB is None:
        _struct_2I6fB = struct.Struct("<2I6fB")
    return _struct_2I6fB
