frame_id: 'Robot?'
outlierRemoval_MeanK: 75
outlierRemoval_StdDev: 2
outlierRemoval_SearchRadius: 25
outlierRemoval_MinNeighborsInRadius: 10

passThrough_Xmin: -5
passThrough_Xmax:  5

passThrough_Ymin:  -1
passThrough_Ymax:  .85

passThrough_Zmin:  0
passThrough_Zmax:  3

alpha: -M_PI/2
beta: 0.0
gamma: 0.0
xTrans: 0.0
yTrans: 0.0
zTrans: 0.0

don_scale1: 0.15
don_scale2: 0.22
don_threshold: 0.15
don_segradius: 0.1

don_minClusterSize: 500
don_maxClusterSize: 80000

statOutlier_meanK: 150
statOutlier_stdDev: .1

passThrough_BoxMargin: 1.5

plane_DistThresh: .05
plane_LeafSize: 0.01
don_Scale1: .3
don_Scale2: 20
don_Threshold: .05
don_Segradius: 1
don_MinClusterSize: 200
don_maxClusterSize: 2000

